---
# HassUnpauseTimer - default
# example: nadaljuj časovnik

language: "sl"
data:
  - sentences:
      - "nadaljuj [moj] (časovnik|timer|tajmer|štoparico|odštevalnik)"
      - "nadaljuj s (časovnikom|timerjem|tajmerjem|štoparico|odštevalnikom)"
    example: "nadaljuj časovnik"
    response: "default"
  - sentences:
      - "nadaljuj časovnik"
      - "nadaljuj timer"
    example: "nadaljuj časovnik"
    response: "default"
    speech_to_phrase: true
