---
# HassMediaUnpause - default
# context_area: true

language: "sl"
data:
  - sentences:
      - "nadaljuj [predvajanje|glasbo|video|film] [<here>]"
      - "predvajaj (naprej|dalje) [<here>]"
    example: "nadaljuj predvajanje"
    response: "default"
  - sentences:
      - "nadaljuj"
    example: "nadaljuj"
    response: "default"
    speech_to_phrase: true
