# HassMediaPlayerUnmute - default
language: eu
data:
  - sentences:
      - "<soinua_piztu>"
      - "<soinua_piztu> <media>"
      - "<media> <soinua_piztu>"
    example: "soinua piztu"
    response: "default"
