---
# HassCancelTimer - default
# example: cancel my timer

language: "ru"
data:
  - sentences:
      - "<timer_cancel> таймер"
    example: "выключи таймер"
    response: "default"
  - sentences:
      - "выключи таймер"
      - "останови таймер"
    example: "выключи таймер"
    response: "default"
    speech_to_phrase: true
