# HassMediaSearchAndPlay - default
language: eu
data:
  - sentences:
      - "<media_jarri> {search_query}"
      - "{search_query} <media_jarri>"
    example: "jarri Pink Floyd"
    response: "default"
