---
# HassNevermind - default

language: "sl"
data:
  - sentences:
      - "prekini"
      - "odnehaj"
      - "prekliči"
      - "nima veze"
      - "pozabi [na] [to] [kar sem rek[el|la]]"
    example: "prekini"
    response: "default"
  - sentences:
      - "pozabi"
      - "prekini"
    example: "pozabi"
    response: "default"
    speech_to_phrase: true
