---
# HassTimerStatus - default

language: "ru"
data:
  - sentences:
      - "что с (таймером|таймерами)"
      - "[какое ]состояние [у] (таймера|таймеров)"
      - "сколько [времени] осталось у (таймера|таймеров)"
      - "сколько [времени] осталось на (таймере|таймерах)"
    example: "что с таймерами"
    response: "default"
  - sentences:
      - "какое состояние у таймеров"
      - "сколько осталось на таймерах"
    example: "сколько осталось на таймерах"
    response: "default"
    speech_to_phrase: true
