language: eu
data:
  - sentences:
      - "zein da [orain] tenperatura [<hemen>]"
      - "zenbat gradu daude [<hemen>]"
      - "(esadazu|esaidazu|esan) [orain] tenperatura [<hemen>]"
    example: "zein da tenperatura"
    response: default
