# HassSetVolumeRelative - default
language: eu
data:
  - sentences:
      - "{volume_step:volume_step} <bolumena>"
      - "<bolumena> {volume_step:volume_step}"
      - "<volume_up> <bolumena> [%|ehuneko ]{volume_step_up:volume_step}"
      - "<volume_down> <bolumena> [%|ehuneko ]{volume_step_down:volume_step}"
    example: "igo bolumena"
    response: "default"
