# HassLawnMowerStartMowing - default
language: eu
data:
  - sentences:
      - "<mozten_hasi>"
      - "<abiarazi> <belar_mozgailua>"
      - "<belar_mozgailua> <abiarazi>"
    example: "hasi mozten"
    response: "default"
