# HassFanSetSpeed - default
language: eu
data:
  - sentences:
      - "<zenbakia_ezarri> <haizegailua>ren <abiadura> [%|ehuneko ]{fan_speed:percentage}[era]"
      - "<zenbakia_ezarri> <haizegailua>[k] [<abiadura>] [%|ehuneko ]{fan_speed:percentage}[era]"
      - "<abiadura> [%|ehuneko ]{fan_speed:percentage}[era] <zenbakia_ezarri>"
    example: "ezarri haizegailuaren abiadura %50era"
    response: "default"
