---
# HassGetCurrentTime - default

language: "sl"
data:
  - sentences:
      - "([povej [mi]]) koliko je ura"
      - "trenutna ura"
      - "([povej [mi]]) trenuten čas"
    example: "koliko je ura"
    response: "default"
  - sentences:
      - "koliko je ura"
    example: "koliko je ura"
    response: "default"
    speech_to_phrase: true
