---
# HassGetCurrentDate - default

language: "sl"
data:
  - sentences:
      - "([povej [mi]] kateri|katerega) [smo] [dan je] danes"
      - "([povej [mi]] današnji datum)"
      - "([povej [mi]] kateri dan je [danes])"
      - "([povej [mi]] kateri je danes)"
      - "([povej [mi]] kirega smo [danes])"
    example: "kateri dan je danes"
    response: "default"
  - sentences:
      - "kateri dan je danes"
    example: "kateri dan je danes"
    response: "default"
    speech_to_phrase: true
