---
# HassGetWeather - default
# example: какая погода

language: "ru"
data:
  - sentences:
      - "[Какая ][сейчас ] погода"
    example: "какая погода"
    response: "default"
  - sentences:
      - "погода"
      - "какая сейчас погода"
    example: "погода"
    response: "default"
    speech_to_phrase: true
