---
# HassClimateGetTemperature - default
# example: kakšna je temperatura
# context_area: true

language: "sl"
data:
  - sentences:
      - "(kakšna|kaksna) je <temp> [<here>]"
      - "koliko stopinj je [<here>]"
      - "povej mi <temp> [<here>]"
      - "ali je (toplo|hladno|vroče|vroce) [<here>]"
    example: "kakšna je temperatura"
    response: "default"
  - sentences:
      - "kakšna je temperatura"
    example: "kakšna je temperatura"
    response: "default"
    speech_to_phrase: true
