---
# HassGetCurrentTime - default
# example: сколько времени

language: "ru"
data:
  - sentences:
      - "какое [сейчас] время"
      - "который [сейчас] час"
      - "сколько [сейчас] времени"
      - "[под]скажи [мне] время"
      - "назови [мне] время"
    example: "сколько времени"
    response: "default"
  - sentences:
      - "который час"
      - "сколько времени"
    example: "сколько времени"
    response: "default"
    speech_to_phrase: true
