---
# HassPauseTimer - default
# example: pause my timer

language: "ru"
data:
  - sentences:
      - "поставь таймер на паузу"
      - "[при]останови таймер"
      - "пауза таймера"
    example: "pause my timer"
    response: "default"
  - sentences:
      - "останови таймер"
    example: "останови таймер"
    response: "default"
    speech_to_phrase: true
