language: eu
data:
  - sentences:
      - "zein da eguraldia"
      - "nola dago eguraldia"
      - "nolako eguraldia egiten du"
      - "(esadazu|esaidazu|esan) eguraldia"
    example: "zein da eguraldia"
    response: default
