# HassRespond - default
language: eu
data:
  - sentences:
      - "(kaixo|egun on) [home assistant]"
    example: "kaixo"
    response: "hello"
  - sentences:
      - "beti zaude (entzuten|grabatzen)"
    example: "beti zaude entzuten"
    response: "listening"
  - sentences:
      - "nora doaz nire datuak"
    example: "nora doaz nire datuak"
    response: "data"
  - sentences:
      - "zer esan dezaket"
    example: "zer esan dezaket"
    response: "commands"
  - sentences:
      - "nork sortu zaitu"
    example: "nork sortu zaitu"
    response: "creator"
