---
# HassCancelAllTimers - default
# example: prekliči vse časovnike

language: "sl"
data:
  - sentences:
      - "<timer_cancel> vse [moje] (časovnike|timerje|tajmerje|štoparice|odštevalnike)"
    example: "prekliči vse časovnike"
    response: "default"
  - sentences:
      - "ustavi vse časovnike"
    example: "ustavi vse časovnike"
    response: "default"
    speech_to_phrase: true
