language: eu
data:
  - sentences:
      - "<timer_unpause> <tenporizadorea>"
      - "<tenporizadorea> <timer_unpause>"
      - "<timer_unpause> tenporizadorearekin"
    example: "berrekin tenporizadorea"
    response: "default"
