---
# HassNevermind - default
# example: отмена

language: "ru"
data:
  - sentences:
      - "Отмена"
      - "Проехали"
      - "Забудь"
      - "Забей"
      - "Неважно"
      - "Отбой"
    example: "отмена"
    response: "default"
  - sentences:
      - "Отмена"
      - "Забудь"
    example: "Отмена"
    response: "default"
    speech_to_phrase: true
