---
# HassCancelTimer - default
# example: prekliči časovnik

language: "sl"
data:
  - sentences:
      - "<timer_cancel> [moj] (časovnik|timer|tajmer|štoparico|odštevalnik)"
      - "[moj] (časovnik|timer|tajmer|štoparico|odštevalnik) <timer_cancel>"
    example: "prekliči časovnik"
    response: "default"
  - sentences:
      - "ustavi časovnik"
      - "ustavi timer"
    example: "ustavi časovnik"
    response: "default"
    speech_to_phrase: true
