language: eu
data:
  - sentences:
      - "tenporizadorearen egoera"
      - "zenbat [denbora] falta zaio tenporizadoreari"
      - "noiz amaituko da <tenporizadorea>"
    example: "tenporizadorearen egoera"
    response: "default"
