# HassSetVolume - default
language: eu
data:
  - sentences:
      - "<zenbakia_ezarri> <bolumena> [%|ehuneko ]{volume:volume_level}[era]"
      - "<bolumena> [%|ehuneko ]{volume:volume_level}[era] <zenbakia_ezarri>"
      - "[%|ehuneko ]{volume:volume_level}[era] <zenbakia_ezarri> <bolumena>"
    example: "ezarri bolumena %50era"
    response: "default"
