---
# HassTimerStatus - default
# example: status časovnika

language: "sl"
data:
  - sentences:
      - "(časovnik|timer|tajmer|štoparica|odštevalnik) status"
      - "[kakšen je] status [moj[ega|e|ih]] (časovnik[ov|a]|timer[jev|ja]|tajmer[jev|ja]|štoparic[e|a]|odštevalnik[ov|a])"
      - "[koliko časa] je [preostalo|ostalo] na [mojem|mojemu|moji|mojih] (časovnik[u|ih]|timer[jih|ju]|tajmer[ju|jih]|štoparic[i|ah|ama]|odštevalnik[u|ih])"
    example: "status časovnika"
    response: "default"
  - sentences:
      - "status časovnika"
      - "koliko časa je ostalo na časovniku"
    example: "status časovnika"
    response: "default"
    speech_to_phrase: true
