language: eu
data:
  - sentences:
      - "<timer_cancel> <tenporizadore_guztiak>"
      - "<tenporizadore_guztiak> <timer_cancel>"
    example: "ezeztatu tenporizadore guztiak"
    response: "default"
