---
# HassMediaNext - default
# example: следующий трек
# context_area: true

language: "ru"
data:
  - sentences:
      - "включи следующ(ий|ую) [трек|песню]"
      - "переключи на следующ(ий|ую) [трек|песню]"
      - "следующ(ий|ая) (трек|песня)"
    example: "Следующий трек"
    response: "default"
  - sentences:
      - "следующая песня"
      - "следующий трек"
    example: "следующая песня"
    response: "default"
    speech_to_phrase: true
