# HassLawnMowerDock - default
language: eu
data:
  - sentences:
      - "<mozten_utzi>"
      - "<etxera_itzuli> <oinarrira>"
      - "<belar_mozgailua> <oinarrira> <etxera_itzuli>"
    example: "mozteari utzi"
    response: "default"
