---
# HassCancelAllTimers - default
# example: cancel all timers

language: "ru"
data:
  - sentences:
      - "<timer_cancel> все таймеры"
    example: "останови все таймеры"
    response: "default"
  - sentences:
      - "выключи все таймеры"
      - "останови все таймеры"
    example: "выключи все таймеры"
    response: "default"
    speech_to_phrase: true
