---
# HassPauseTimer - default
# example: pavziraj časovnik

language: "sl"
data:
  - sentences:
      - "(pavziraj|[daj na] premor|[daj] na pavzo) [moj] (časovnik|timer|tajmer|štoparico|odštevalnik)"
      - "[daj] (časovnik|timer|tajmer|štoparico|odštevalnik) [na] (premor|pavzo)"
    example: "pavziraj časovnik"
    response: "default"
  - sentences:
      - "pavziraj časovnik"
      - "pavziraj timer"
    example: "pavziraj časovnik"
    response: "default"
    speech_to_phrase: true
