---
# HassGetCurrentDate - default
# example: какая сегодня дата

language: "ru"
data:
  - sentences:
      - "какой [сейчас|сегодня] день"
      - "какая [сейчас|сегодня] дата"
      - "какое [сейчас|сегодня] число"
    example: "какая сегодня дата"
    response: "default"
  - sentences:
      - "какое сегодня число"
    example: "какое сегодня число"
    response: "default"
    speech_to_phrase: true
